"""Post-process a CycloneDX SBOM to improve sbomqs quality score.

Enriches the SBOM generated by cyclonedx-py with:
- Metadata: authors, supplier, lifecycle, data license
- Component licenses from installed package metadata
- Component suppliers from author metadata
- Component hashes from distribution files
- Component source code references from Project-URL metadata

Usage:
    poetry run python scripts/enrich_sbom.py sbom.cdx.json
"""

from __future__ import annotations

import importlib.metadata
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

# --- Configuration ---

SBOM_AUTHORS = [
    {
        "name": "Fred Visser",
        "email": "fred.visser@emerson.com",
    }
]

SBOM_SUPPLIER = {
    "name": "NI (Emerson)",
    "url": ["https://github.com/ni-kismet/systemlink-cli"],
}

SBOM_LIFECYCLE = "build"

PROJECT_LICENSE = "MIT"

# Known SPDX license mappings for common non-standard license strings
LICENSE_NORMALIZATIONS: Dict[str, str] = {
    "MIT License": "MIT",
    "MIT license": "MIT",
    "BSD License": "BSD-3-Clause",
    "BSD": "BSD-3-Clause",
    "BSD-3-Clause": "BSD-3-Clause",
    "BSD-2-Clause": "BSD-2-Clause",
    "Apache 2.0": "Apache-2.0",
    "Apache-2.0": "Apache-2.0",
    "Apache Software License": "Apache-2.0",
    "ISC License": "ISC",
    "ISC license": "ISC",
    "ISC": "ISC",
    "PSF": "PSF-2.0",
    "Python Software Foundation License": "PSF-2.0",
    "LGPL-3.0": "LGPL-3.0-only",
    "GPL-3.0": "GPL-3.0-only",
    "MPL-2.0": "MPL-2.0",
    "MPL 2.0": "MPL-2.0",
}


def normalize_license(raw: Optional[str]) -> Optional[str]:
    """Normalize a license string to SPDX identifier."""
    if not raw or raw.lower() in ("unknown", "none", ""):
        return None
    raw = raw.strip()
    if raw in LICENSE_NORMALIZATIONS:
        return LICENSE_NORMALIZATIONS[raw]
    # If it looks like it's already SPDX (no spaces, has dash pattern)
    if re.match(r"^[A-Za-z0-9][A-Za-z0-9._-]*$", raw):
        return raw
    return None


def get_package_metadata() -> Dict[str, Dict[str, Any]]:
    """Collect metadata for all installed Python packages."""
    packages: Dict[str, Dict[str, Any]] = {}
    for dist in importlib.metadata.distributions():
        meta = dist.metadata
        name = meta["Name"]
        if not name:
            continue

        # Normalize name to match how cyclonedx-py names components
        normalized = name.lower().replace("-", "-").replace("_", "-")

        license_expr = meta.get("License-Expression") or meta.get("License")
        author = meta.get("Author") or meta.get("Author-email") or ""
        home_page = meta.get("Home-page") or ""

        # Parse Project-URL for VCS links
        vcs_url = None
        project_urls_raw = meta.get_all("Project-URL") or []
        for url_entry in project_urls_raw:
            if "," in url_entry:
                label, url = url_entry.split(",", 1)
                label = label.strip().lower()
                url = url.strip()
                if label in ("source", "source code", "repository", "vcs", "code"):
                    vcs_url = url
                    break
        if not vcs_url and home_page and "github.com" in home_page:
            vcs_url = home_page

        # Get hash from dist files (RECORD uses base64url, CycloneDX needs hex)
        file_hashes: List[Dict[str, str]] = []
        if dist.files:
            record_file = dist._path / "RECORD"  # type: ignore[attr-defined]
            if record_file.exists():
                for line in record_file.read_text().splitlines():
                    parts = line.split(",")
                    if len(parts) >= 2 and parts[1].startswith("sha256="):
                        b64_hash = parts[1].replace("sha256=", "")
                        # Convert base64url to hex
                        import base64

                        try:
                            # Add padding if needed
                            padded = b64_hash + "=" * (4 - len(b64_hash) % 4)
                            hex_hash = base64.urlsafe_b64decode(padded).hex()
                            if len(hex_hash) == 64:  # Valid SHA-256 hex
                                file_hashes.append({"alg": "SHA-256", "content": hex_hash})
                                break
                        except Exception:
                            pass

        packages[normalized] = {
            "license": license_expr,
            "author": author,
            "vcs_url": vcs_url,
            "hashes": file_hashes,
        }

    return packages


def enrich_metadata(sbom: Dict[str, Any]) -> None:
    """Add authors, supplier, lifecycle, and data license to SBOM metadata."""
    metadata = sbom.setdefault("metadata", {})

    # Add authors (organizationalContact array)
    metadata["authors"] = SBOM_AUTHORS

    # Add manufacturer (the org that built the BOM)
    metadata["manufacturer"] = SBOM_SUPPLIER

    # Add supplier at metadata level (the org supplying the software)
    metadata["supplier"] = SBOM_SUPPLIER

    # Add supplier to metadata.component as well
    component = metadata.get("component", {})
    component["supplier"] = SBOM_SUPPLIER

    # Add project license to metadata component
    component.setdefault("licenses", []).append(
        {"license": {"id": PROJECT_LICENSE, "acknowledgement": "declared"}}
    )

    # Add lifecycle
    metadata["lifecycles"] = [{"phase": SBOM_LIFECYCLE}]

    # Add data license (CC0-1.0 is the standard for CycloneDX SBOMs)
    metadata["licenses"] = [{"license": {"id": "CC0-1.0"}}]


def enrich_components(sbom: Dict[str, Any], packages: Dict[str, Dict[str, Any]]) -> None:
    """Enrich components with license, supplier, hashes, and source code info."""
    for comp in sbom.get("components", []):
        name = comp.get("name", "").lower().replace("_", "-")
        pkg_meta = packages.get(name)
        if not pkg_meta:
            continue

        # Add license (mark as concluded - the SBOM tool determined the license)
        if not comp.get("licenses"):
            spdx_id = normalize_license(pkg_meta.get("license"))
            if spdx_id:
                comp["licenses"] = [{"license": {"id": spdx_id, "acknowledgement": "concluded"}}]

        # Add supplier from author
        if not comp.get("supplier") and pkg_meta.get("author"):
            author = pkg_meta["author"]
            # Parse "Name <email>" format
            email_match = re.match(r"(.+?)\s*<(.+?)>", author)
            if email_match:
                comp["supplier"] = {
                    "name": email_match.group(1).strip(),
                    "contact": [{"email": email_match.group(2).strip()}],
                }
            else:
                comp["supplier"] = {"name": author}

        # Add VCS external reference for source code
        if pkg_meta.get("vcs_url"):
            ext_refs = comp.setdefault("externalReferences", [])
            has_vcs = any(r.get("type") == "vcs" for r in ext_refs)
            if not has_vcs:
                ext_refs.append({"type": "vcs", "url": pkg_meta["vcs_url"]})

        # Add hashes from distribution metadata
        if not comp.get("hashes") and pkg_meta.get("hashes"):
            comp["hashes"] = pkg_meta["hashes"]

        # Add CPE 2.3 identifier derived from purl
        if not comp.get("cpe") and comp.get("purl"):
            purl_str = comp["purl"]
            # Parse pkg:pypi/name@version
            purl_match = re.match(r"pkg:pypi/([^@?#]+)@([^?#]+)", purl_str)
            if purl_match:
                pkg_name = purl_match.group(1).lower().replace("-", "_")
                pkg_version = purl_match.group(2)
                comp["cpe"] = (
                    f"cpe:2.3:a:{pkg_name}_project:{pkg_name}:{pkg_version}" f":*:*:*:*:*:*:*"
                )


def set_compositions(sbom: Dict[str, Any]) -> None:
    """Declare SBOM completeness using compositions."""
    metadata = sbom.get("metadata", {})
    main_ref = metadata.get("component", {}).get("bom-ref")
    if not main_ref:
        return

    # Collect all component bom-refs
    comp_refs = [c["bom-ref"] for c in sbom.get("components", []) if "bom-ref" in c]

    # All dependency refs
    all_dep_refs = [d["ref"] for d in sbom.get("dependencies", [])]

    sbom["compositions"] = [
        {
            "aggregate": "complete",
            "assemblies": [main_ref] + comp_refs,
            "dependencies": all_dep_refs,
        }
    ]


def main() -> None:
    """Enrich a CycloneDX SBOM file in-place."""
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <sbom.cdx.json>", file=sys.stderr)
        sys.exit(1)

    sbom_path = Path(sys.argv[1])
    if not sbom_path.exists():
        print(f"Error: {sbom_path} not found", file=sys.stderr)
        sys.exit(1)

    with open(sbom_path) as f:
        sbom = json.load(f)

    packages = get_package_metadata()

    enrich_metadata(sbom)
    enrich_components(sbom, packages)
    set_compositions(sbom)

    with open(sbom_path, "w") as f:
        json.dump(sbom, f, indent=2)

    # Summary
    comps = sbom.get("components", [])
    with_lic = sum(1 for c in comps if c.get("licenses"))
    with_supplier = sum(1 for c in comps if c.get("supplier"))
    with_vcs = sum(
        1 for c in comps if any(r.get("type") == "vcs" for r in c.get("externalReferences", []))
    )
    print(f"Enriched {sbom_path}:")
    print(f"  Components: {len(comps)}")
    print(f"  With licenses: {with_lic}/{len(comps)}")
    print(f"  With supplier: {with_supplier}/{len(comps)}")
    print(f"  With source code ref: {with_vcs}/{len(comps)}")
    print(f"  Metadata: authors, supplier, lifecycle, data license added")


if __name__ == "__main__":
    main()
